# Generated by Django 3.2.4 on 2022-01-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('cancel_order', 'Can Cancel Order action')]},
        ),
    ]
